---
layout: post
title: "Exception handling - thrrow and try/catch/finally"
author: "Logger"
thumbnail: "https://img1.daumcdn.net/thumb/R750x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F2136834456B940BF29"
tags: 
---


throw

This article will learn how to handle exceptions.

If a problem occurs while the program is running, the program stops automatically.

In this case, it is called exception handling to help the program cope.

Errors that occur during a program`s execution are called exceptions, and grammatical errors in the programming language are called errors.

There may be several reasons for the exception, but you may have written the wrong code or you may have used the program in a direction that the developer did not want.

Exceptions are handled in two ways: basic exception handling and advanced exception handling.

Pre-resolving an exception so that it does not occur is called basic exception processing and can usually be treated as a condition statement.

Here you will learn about advanced exception handling methods during exception handling.

![image](https://t1.daumcdn.net/cfile/tistory/2136834456B940BF29)

### throw

An "Exception" is a signal that indicates an exceptional situation or error has occurred.

The `throw` of an exception means to inform such an error or exception situation.

On the other hand, `catch` an exception means taking care of it (i.e., taking something necessary or appropriate action to recover from the exception).

JavaScript generates an exception whenever a runtime error occurs. The program also uses the `throw` statement to create exceptions explicitly.

Use the "throw" keyword when this exception is forced.

Use the `try/catch/final` statement to capture the exception.

The syntax for the throw statement is as follows:

```js
'Throw expression;'
```

The resultant type of `expression` can be anything. However, most of those types often become instances of one of the Error objects or subclasses of Error.

Sometimes a string containing an error message or a numeric value indicating any error code can be useful.

The following example code looks at how the throw statement is used to generate an exception:

```js
function factorial(x) {
// If the transfer factor is not valid, create an exception!!!
if (x < 0) {
thrrow new Error('x) must not be negative.')
}
// If valid, calculate the value and return it normally.
for (var f = 1; x > 1; f *= x, x--) /* empty */
return f;
}
```

When an exception occurs, the JavaScript interpreter immediately stops running the normal program and moves on to the nearest exception handler.

The exception handler is created using the `catch` clause in the `try/catch/final` statements to be addressed.

If the code block that caused the exception is not associated with the catch clause, the interpreter immediately checks that it is connected to the code block surrounding the higher level. This process repeats until the handler is found.

If an exception occurs within a function that does not have a try/catch/finally statement to handle the exception, the exception is propagated and raised to the block where it was called.

In this way, exceptions are propagated and raised along the linguistic structure of JavaScript, i.e., the call stack. If no exception handler is found, this exception will be treated as an error and reported to the user.

### try/catch/finally

The statement `try/catch/final` is an exception handling technique in JavaScript.

In this sentence, the `try` clause simply defines a block of code that may result in an exception to process. The try block is followed by the `catch` clause.

The catch clause is the sentence block called when an exception occurs inside the try block.

The catch clause is followed by a `finally` block, which includes a clean-up code that must always be guaranteed to run regardless of what happened in the try block earlier.

You can omit the catch or finally the block. However, try blocks must be used with at least one block, either catch or finally.

The try, catch, and finally blocks all begin with braces and end with braces. These brackets cannot be omitted as part of the required grammar.

Even if there is only one sentence in that section, it is the same.

Use the following code to explore the syntax and purpose of the `try/catch/final` statement.

In particular, look carefully at the parentheses that follow the catch keyword and the identifiers in it.

This identifier resembles the transfer factor of the function, which names a local variable that exists only inside the body of the catch block.

Whatever the exception object or value was thrown earlier, it will be assigned to this variable.

```js
try {
/**
* If normal, this code runs from start to end of the block without any problems.
* However, exceptions may occur in some cases.
* Exceptions may be directly caused by the thrrow statement.
* Or it can be caused by a call from a method that causes an exception.
*/
} catch (e) {
/**
* Sentences inside this block are executed only when an exception occurs in the try block.
* These statements use the local variable e to refer to the Error object or other values thrown earlier.
* This block can somehow handle the exception.
* You can just do nothing and ignore the exception.
* Or you can re-occur an exception using throw.
*/
} finally {
/**
* This block contains code to execute unconditionally, regardless of what happened in the try block.
* This code is executed when the try block somehow terminates.
* Try Block termination is as follows.
* 1) When the end of the block is reached normally,
* 2) By break, continue, or return door
* 3) Exception occurred, but when handled in catch section
* 4) When an exception occurs and spreads without being caught,
*/
}
```

The following is a more practical example of a try/catch statement. This uses the previously used formula() method.

```js
try {
// Ask the user to enter a number
van = prompt ("Please enter an integer").");
// Suppose the user's input is valid and calculates the number of successions.
var f = factorial(n);
// display the results.
console.log(n + "! = " + f);
} Catch (ex) {// reach here if the user's input is not valid.
// Inform the user what the error is.
alert(ex);
}
```

The code above is an example of a try/catch statement without a clause finally. Finally, it is not used as often as catch, but it is often useful.

However, further explanation is required to understand the operation of the final. Once a try block is run even partially, the clause is finally guaranteed to run.

It doesn`t matter how the code of the try block ends. Finally, clauses are commonly used for cleaning up the try clause code.

In normal cases, after the program control is reached to the end of the try block, the control proceeds to the final block to perform the necessary cleanup.

If the control is withdrawn from the try block due to return, continue, break, etc., the block is finally executed before the control is moved to the place where these sentences lead.

If there is an exception in the try block and there is a catch block to handle this exception, the control will be moved to the catch block and finally come over to the block.

If the catch block that handles the exceptions that occur is not in the current stage, then the control will move to the block finally, then propagate to the higher level, and then move up to the nearest catch clause where the exception can be processed.

Finally, you can move control from the block itself by using return, continue, break, or throw statements, or by calling a method that causes an exception.

In this case, the control movement that was supposed to occur after the block was finally executed is canceled. Instead, a new control shift will occur, pointing to the final.

For example, if you create an exception in the clause finally, that exception occurs and replaces the exception that was being processed.

If the return statement was finally executed in the clause, this method would be returned normally even if an exception had been made and has not yet been processed.

Try and finally can be used together without a catch.

In this case, regardless of whether the try, continue, or return statements are executed in the try clause, the final block will serve as a clean-up code that is guaranteed to be executed unconditionally.

For example, the following code uses a try/final statement to allow the loop counter variable to increase normally:

The loop counter variable is the code that increases even if the loop iteration ends suddenly by the continuue statement.

```js
var i = 0, total = 0;
while (i < a.length) {
try {
if(typeofa[i] != 'number' || isNaN(a[i])) {/ if this is not a number
Continue; // to the next iteration of this loop.
}
If total += a[i]; // is a number, add this number to total.
} finally {
i++; // use continuue above, but make sure to increase i.
}
}
```

Let`s look at another code.

```js
// try ~ catch ~ finally clause : exception handling syntax in JavaScript (similar to C#/Java)
// fake(); // An error occurs by calling an undefined function
try {
// Enter the code that might cause an exception (error)
fake(); // call undefined function
} catch (e) {
// Area that runs when an exception occurs
alert(e.name + ", " + e.message);
} finally {
// Areas that run unconditionally with or without exceptions
alert('Unconditional Execution Area')
}
```

```js
// create an exception unconditionally
// thrrow {name : 'Exception Name', message : 'Exception Content'}
try {
var a = 3;
var b = 0;
if(b === 0 ) {
row {name : 'divideByZeroException', message: 'Can't be divided by 0'}
}
} catch (e) {
alert (e.name + ", " + e.message); // extraneous processing syntax (e.g. to ensure normal termination of abnormal termination)
} finally {
alert('Exit program normally')
}
```